/*
 * Accesa fork — Digital Euro extensions to the EUDI reference wallet.
 * SPDX-License-Identifier: EUPL-1.2
 *
 * Simulated Secure Element applet contract per
 * `specs/components/mobile-wallet.md` §M4a handoff. Treated like a real SE:
 * no callers outside `de-feature` reach in, and any operation that the
 * real SE applet would atomic-counter-protect goes through this interface.
 *
 * **Workshop only.** A real SE applet would refuse to release the same
 * token for a transfer twice (per-token serial + per-wallet monotonic
 * `txCounter` enforcement at the silicon boundary). The simulated SE
 * keeps the data model and the operation surface honest; the trust
 * anchor is app code, clearly labelled "Simulated SE — workshop demo"
 * everywhere this module's state is the source of truth.
 */

package eu.europa.ec.destorage

import kotlinx.serialization.json.JsonObject
import java.time.Instant

interface SimulatedSecureElement {
    /**
     * Generate a fresh EC P-256 keypair for binding offline tokens. The
     * private key is held in encrypted storage under a generated alias.
     * Returns the public JWK to embed in the withdraw envelope's
     * `holderPub` field before signing.
     *
     * One keypair per withdraw operation. Aliases are never reused.
     */
    suspend fun generateHolderKey(): HolderKeyHandle

    /**
     * Persist newly minted tokens received from the bank's `/deliver`
     * endpoint. Verifies each token's JWS against the NCB cert chain
     * (cached) and rejects any whose embedded `holderPub` does not match
     * the keypair just generated by [generateHolderKey].
     *
     * Atomically increments [txCounter]. Idempotent on `serial` —
     * re-storing the same serial is a no-op (defence-in-depth against a
     * retry causing duplicates).
     *
     * Slice 3 ships a no-verify stub of this method — every supplied
     * token is accepted as long as the handle's alias matches.
     * Signature + holderPub verification lands in slice 4 with the
     * delivery client and the bundled NCB trust root.
     */
    suspend fun storeTokens(
        handle: HolderKeyHandle,
        tokens: List<OfflineTokenJws>,
    ): StoreResult

    /** Total amount of unspent tokens held, in EUR cents. */
    suspend fun offlineBalance(): Long

    /** Token list for the holdings drill-in screen. Never returns private keys. */
    suspend fun listHeldTokens(): List<HeldToken>

    /**
     * Current monotonic counter. Increments on every storage-touching
     * operation. Exposed for diagnostics; the UI uses [offlineBalance].
     */
    suspend fun txCounter(): Long

    /**
     * Wipe all simulated-SE state. Used by the workshop reset flow
     * (long-press About) alongside `WalletStateRepository.clear()`.
     */
    suspend fun reset()
}

/**
 * Public side of a freshly generated holder keypair. The bank's
 * `/deliver` request body carries `publicJwk` verbatim; the bank
 * backend deep-equal-checks it against `envelope.holderPub` in the
 * signed authorisation JWT.
 */
data class HolderKeyHandle(
    val alias: String,           // SE storage alias
    val publicJwk: JsonObject,   // EC P-256 JWK for embedding in the envelope
)

/**
 * Token as received from the bank's `/deliver` endpoint. `jws` is the
 * compact-serialised `de-offline+jwt` per [ADR 0010]; the wallet keeps
 * it verbatim for redemption (M4c).
 */
data class OfflineTokenJws(
    val serial: String,
    val amount: Long,
    val currency: String,
    val jws: String,
)

/** Token entry exposed to the holdings drill-in screen. */
data class HeldToken(
    val serial: String,
    val amount: Long,
    val currency: String,
    val ncbBic: String,
    val issuedAt: Instant,
    val expiry: Instant,
)

sealed class StoreResult {
    data class Ok(
        val storedCount: Int,
        val newBalance: Long,
        val newTxCounter: Long,
    ) : StoreResult()

    data class PartialOk(
        val storedCount: Int,
        val rejectedSerials: List<String>,
        val reason: String,
    ) : StoreResult()

    data class Rejected(val reason: String) : StoreResult()
}
