/*
 * Accesa fork — Digital Euro extensions to the EUDI reference wallet.
 * SPDX-License-Identifier: EUPL-1.2
 *
 * Simulated Secure Element applet contract per
 * `specs/components/mobile-wallet.md` §M4a + §M4b/c handoff. Treated like a
 * real SE: no callers outside `de-feature` reach in, and any operation that
 * the real SE applet would atomic-counter-protect goes through this
 * interface.
 *
 * **Workshop only.** A real SE applet would refuse to release the same
 * token for a transfer twice (per-token serial + per-wallet monotonic
 * `txCounter` enforcement at the silicon boundary). The simulated SE
 * keeps the data model and the operation surface honest; the trust
 * anchor is app code, clearly labelled "Simulated SE — workshop demo"
 * everywhere this module's state is the source of truth.
 */

package eu.europa.ec.destorage

import eu.europa.ec.delogic.delivery.SerialStatus
import kotlinx.serialization.json.JsonObject
import java.time.Instant

interface SimulatedSecureElement {
    /**
     * Generate a fresh EC P-256 keypair for binding offline tokens. The
     * private key is held in encrypted storage under a generated alias.
     * Returns the public JWK to embed in the withdraw envelope's
     * `holderPub` field before signing.
     *
     * One keypair per withdraw operation. Aliases are never reused.
     */
    suspend fun generateHolderKey(): HolderKeyHandle

    /**
     * Persist newly minted tokens received from the bank's `/deliver`
     * endpoint. Verifies each token's JWS against the NCB cert chain
     * (cached) and rejects any whose embedded `holderPub` does not match
     * the keypair just generated by [generateHolderKey].
     *
     * Atomically increments [txCounter]. Idempotent on `serial` —
     * re-storing the same serial is a no-op (defence-in-depth against a
     * retry causing duplicates).
     *
     * [reconciliationUrl] is the bank's serial-status base URL from the
     * `/withdraw-to-wallet/deliver` response (ADR 0011 §8). Stored per
     * token so the reconcile job can route status queries to the
     * issuing bank. Nullable for backward-compat with pre-M4b/c bank
     * builds.
     */
    suspend fun storeTokens(
        handle: HolderKeyHandle,
        tokens: List<OfflineTokenJws>,
        reconciliationUrl: String? = null,
    ): StoreResult

    /** Total amount of LIVE (spendable) tokens held, in EUR cents. */
    suspend fun offlineBalance(): Long

    /** Token list for the holdings drill-in screen. Never returns private keys. */
    suspend fun listHeldTokens(): List<HeldToken>

    /**
     * Current monotonic counter. Increments on every storage-touching
     * operation. Exposed for diagnostics; the UI uses [offlineBalance].
     */
    suspend fun txCounter(): Long

    /**
     * Wipe all simulated-SE state. Used by the workshop reset flow
     * (long-press About) alongside `WalletStateRepository.clear()`.
     */
    suspend fun reset()

    // ─── M4b/c surface ────────────────────────────────────────────────────────

    /**
     * Sender side (ADR 0011 §5). Build a TransferProof for each token in
     * [serials], addressed to [recipientHolderPub]. Marks the source
     * tokens OUTGOING_PENDING in persistent storage. Each TransferProof
     * carries a fresh senderTxCounter that the SE refuses to reuse with
     * the same serial.
     *
     * Returns the signed proofs ready to send over the NFC handshake.
     * Throws [IllegalStateException] if any serial is missing, not in
     * LIVE state, or signs to a different amount than the caller asked
     * for.
     */
    suspend fun signTransferProofs(
        serials: List<String>,
        recipientHolderPub: JsonObject,
        currency: String,
    ): List<TransferProofJws>

    /**
     * Recipient side (ADR 0011 §5). Verifies each (token, transferProof)
     * pair against the bundled NCB workshop root + the token's
     * `holderPub`, cross-checks the proof's `toHolderPub` against
     * [ourHolderPub], and persists accepted items as INCOMING_PENDING
     * with the [IncomingItem.reconciliationUrl] attached.
     */
    suspend fun acceptIncoming(
        ourHolderPub: HolderKeyHandle,
        items: List<IncomingItem>,
    ): AcceptResult

    /**
     * Wallet-direct call to the bank's serial-status proxy (ADR 0011 §8
     * amendment). Used by the reconcile pass to decide rollback vs
     * finalise for OUTGOING and INCOMING pending entries.
     */
    suspend fun serialStatus(serial: String, reconciliationUrl: String): SerialStatus

    /**
     * Scheduled / on-reconnect reconcile pass. For each OUTGOING_PENDING
     * past expiry: query the issuing bank, restore-or-consume. For each
     * INCOMING_PENDING past expiry: query the sender's bank, finalise-or-
     * drop. Returns the per-bucket serial lists for UI refresh.
     */
    suspend fun reconcilePending(): ReconcileResult

    /**
     * Self-redeem helper (M4c-self-redeem). Picks LIVE tokens summing to
     * [amount] (LIFO), builds a self-TransferProof per token (fromHolderPub
     * == toHolderPub == token.holderPub, signed by token.holderPub
     * private key). Does NOT yet mark tokens spent — the caller invokes
     * [commitRedeemed] on a successful `/redeem-self/deliver` 200.
     *
     * Returns `null` if the LIVE tokens can't sum to [amount] exactly
     * (workshop tokens are denominated €5/€10/€20/€50).
     */
    suspend fun buildSelfRedeem(amount: Long, currency: String): SelfRedeemBundle?

    /**
     * Called on a successful `/sync/deliver` or `/redeem-self/deliver`
     * response. Removes the listed tokens from local storage, increments
     * [txCounter], and decrements [offlineBalance].
     */
    suspend fun commitRedeemed(serials: List<String>)
}

/**
 * Public side of a freshly generated holder keypair. The bank's
 * `/deliver` request body carries `publicJwk` verbatim; the bank
 * backend deep-equal-checks it against `envelope.holderPub` in the
 * signed authorisation JWT.
 */
data class HolderKeyHandle(
    val alias: String,           // SE storage alias
    val publicJwk: JsonObject,   // EC P-256 JWK for embedding in the envelope
)

/**
 * Token as received from the bank's `/deliver` endpoint. `jws` is the
 * compact-serialised `de-offline+jwt` per [ADR 0010]; the wallet keeps
 * it verbatim for redemption (M4c).
 */
data class OfflineTokenJws(
    val serial: String,
    val amount: Long,
    val currency: String,
    val jws: String,
)

/**
 * Token entry exposed to the holdings drill-in screen + the send flow.
 *
 * [jws] and [reconciliationUrl] are populated for any token persisted
 * via M4a withdraw (PR23 onwards). The holdings drill-in does not
 * render them; the send flow uses [reconciliationUrl] to build the
 * NFC transferOffer and [jws] to build the transferCommit. Empty /
 * null values exist only for pre-M4a-PR23 rows that predate the
 * column migration — safe to skip those for outbound transfers.
 */
data class HeldToken(
    val serial: String,
    val amount: Long,
    val currency: String,
    val ncbBic: String,
    val issuedAt: Instant,
    val expiry: Instant,
    val state: TokenState,
    val transferExpiry: Instant? = null,
    val jws: String = "",
    val reconciliationUrl: String? = null,
)

/**
 * Spendable life-cycle state of an offline token (ADR 0011 §7).
 *  - LIVE              — spendable.
 *  - OUTGOING_PENDING  — promised away via NFC; awaiting recipient sync or 5-min expiry.
 *  - INCOMING_PENDING  — received via NFC; awaiting sync to the recipient's bank.
 *  - CONSUMED          — finalised (either sent + recipient synced, or redeemed); kept for short-term audit.
 */
enum class TokenState { LIVE, OUTGOING_PENDING, INCOMING_PENDING, CONSUMED }

sealed class StoreResult {
    data class Ok(
        val storedCount: Int,
        val newBalance: Long,
        val newTxCounter: Long,
    ) : StoreResult()

    data class PartialOk(
        val storedCount: Int,
        val rejectedSerials: List<String>,
        val reason: String,
    ) : StoreResult()

    data class Rejected(val reason: String) : StoreResult()
}

/**
 * Compact-serialised `de-transferproof+jwt` per ADR 0011 §5, bound to
 * a specific token serial.
 */
data class TransferProofJws(val tokenSerial: String, val jws: String)

/**
 * One inbound token + its accompanying TransferProof, as delivered over
 * the NFC `transferCommit` message. [reconciliationUrl] is the sender's
 * bank URL (delivered separately via `transferOffer`); the SE stores it
 * per token so a recipient reconcile pass can call the right bank.
 */
data class IncomingItem(
    val token: OfflineTokenJws,
    val transferProof: TransferProofJws,
    val reconciliationUrl: String,
)

sealed class AcceptResult {
    data class Ok(val acceptedCount: Int) : AcceptResult()
    data class PartialOk(val accepted: Int, val rejected: List<Rejection>) : AcceptResult()
    data class AllRejected(val rejections: List<Rejection>) : AcceptResult()
}

data class Rejection(val serial: String, val reason: RejectionReason)

enum class RejectionReason {
    TOKEN_SIGNATURE_INVALID,
    TOKEN_EXPIRED,
    TRANSFER_PROOF_SIGNATURE_INVALID,
    TRANSFER_PROOF_EXPIRED,
    TO_HOLDER_PUB_MISMATCH,
    SERIAL_MISMATCH,
    DUPLICATE_SERIAL,
}

data class ReconcileResult(
    val restoredOutgoing: List<String>,
    val finalisedOutgoing: List<String>,
    val finalisedIncoming: List<String>,
    val droppedIncoming: List<String>,
)

data class SelfRedeemBundle(
    val tokens: List<OfflineTokenJws>,
    val transferProofs: List<TransferProofJws>,
    val totalAmount: Long,
)
